### ISSUE TITLE
grover's algorithm won't run from the CLI

### ISSUE THREAD

**Issue by ampolloreno** [rigetticomputing/grove#64]
I think it was broken during the refactor into the amplification module, but here is a traceback trying to run it from the command line:
```
python grover.py 1

Traceback (most recent call last):
  File "grover.py", line 90, in <module>
    oracle = basis_selector_oracle(target, qubits)
  File "grover.py", line 72, in basis_selector_oracle
    np.array([[1, 0], [0, -1]]), 'Z')
  File "/home/ampolloreno/repos/grove/grove/amplification/amplification.py", line 93, in n_qubit_control
    assert len(controls) > 0, "The control qubits list must not be empty"
AssertionError: The control qubits list must not be empty
```

**Comment by ampolloreno** [comment]
Made irrelevant by #89
