### ISSUE TITLE
python3 compatibility issues 

### ISSUE THREAD

**Issue by ryansk10** [rigetticomputing/grove#65]
python3's syntax changes create a couple of problems with grove. Here it's just parenthesis in the `print` function

`python qaoa_rkdemo.py
Traceback (most recent call last):
  File "qaoa_rkdemo.py", line 2, in <module>
    from grove.pyqaoa.maxcut_qaoa import maxcut_qaoa
  File "/Users/Ryan/anaconda3/lib/python3.6/site-packages/grove/__init__.py", line 18, in <module>
    from grove.pyvqe.vqe import VQE
  File "/Users/Ryan/anaconda3/lib/python3.6/site-packages/grove/pyvqe/vqe.py", line 126
    models will be ineffective"""
                                ^
SyntaxError: Missing parentheses in call to 'print'`

**Comment by stevenheidel** [comment]
I believe this is fixed now? @ryansk10

**Comment by ryansk10** [comment]
Yep, good call out.
